In [146]:
import pandas as pd
# Load your dataset
df = pd.read_csv('neg_nuc_data.csv')

print(df.columns)

Index(['Entry', 'Sequence', 'Subcellular location'], dtype='object')


In [147]:
# Export sequences to a FASTA file
with open('Neg_nuc_data.fasta', 'w') as fasta_file:
    for index, row in df.iterrows():
        fasta_file.write(f'>seq{index}\n{row["Sequence"]}\n')

In [148]:
import os

# Run CD-HIT with a threshold of 70% sequence similarity
os.system('cd-hit -i Neg_nuc_data.fasta -o Neg_nuc_cd-hit_data.txt -c 0.7')

Program: CD-HIT, V4.8.1 (+OpenMP), Apr 07 2021, 10:57:21
Command: cd-hit -i Neg_nuc_data.fasta -o
         Neg_nuc_cd-hit_data.txt -c 0.7

Started: Fri May 31 12:47:40 2024
                            Output                              
----------------------------------------------------------------
total seq: 1698
longest and shortest : 4149 and 57
Total letters: 848045
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 1M
Buffer          : 1 X 11M = 11M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 77M

Table limit with the given memory limit:
Max number of representatives: 1004183
Max number of word counting entries: 90269694

comparing sequences from          0  to       1698


.
     1698  finished        305  clusters

Approximated maximum memory consumption: 79M
writing new database
writing clustering information
program completed !

Total CPU time 0.60


0

In [149]:
import pandas as pd
# Load your dataset
df1 = pd.read_csv('Nucleus.csv')

print(df1.columns)

Index(['Entry      ',
       'Sequence                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [150]:
# Strip leading and trailing spaces from column names
df1.columns = df1.columns.str.strip()

# Print cleaned column names to verify
print(df1.columns)

Index(['Entry', 'Sequence', 'Subcellular location'], dtype='object')


In [151]:
# Export sequences to a FASTA file
with open('Nucleus_data.fasta', 'w') as fasta_file:
    for index, row in df1.iterrows():
        fasta_file.write(f'>seq{index}\n{row["Sequence"]}\n')

In [152]:
df1

Entry                                           Sequence  \
0     A0A0L0NNA4   MNLLSILLDNTPPPLMVSLALAPAGHEAPIEGSAKQMPPSLNVTLH...   
1     A0A0L0NNB5   MSYQRAEVYSAQVLPGDQPEDNSFNEITKAFRSFIMEFRLNNSFIY...   
2     A0A0L0NPL2   MDDLNDQVIDAVFSDRVKRFQEFLDQNSENGISHRSAIKDMLMKGK...   
3     A0A0L0NS71   MSSPRKRQADDEDSASERSPPSLASSPQLPPSSPAIPFEDEEEEIH...   
4     A0A0L0NS78   MLFFSFFKTLVDQEIILELKNDIEIKGTLRSVDQYLNLKLDNVSTV...   
...           ...                                                ...   
3010  A0A8F3AHX9   MSRRVDSPQSSASSILYIGSIPFEWSEQNLQAVVSGTAKVLDVRLG...   
3011  A0A8F3AHZ8   MARACVTCKHKKLKCDGERPACGRCCKLGLPCEIPRDKRSDKRKVE...   
3012  A0A8F3AI88   MYTTLQADSLKQIVVQTADEINSENISTVTGKPKRTRSKTGCLCCR...   
3013  A0A8F3AJ57   MNNRNVGALPQQQPQFAIQRPLVTGPAPPAYAAMPVYSYQYMYNSP...   
3014  A0A8F3AJS0   MTMDITPEQVRYIADQLETHTVTFHTIARDLNLHVSQAKRILHAYY...   

     Subcellular location  
0                 Nucleus  
1                 Nucleus  
2                 Nucleus  
3                 Nucleus  
4                 Nucleus  
...                   ...  
3010              Nucleus  
3011              Nucleus  
3012              Nucleus  
3013              Nucleus  
3014              Nucleus  

[3015 rows x 3 columns]

In [153]:
import os

# Run CD-HIT with a threshold of 70% sequence similarity
os.system('cd-hit -i Nucleus_data.fasta -o Nucleus_cd-hit_data.txt -c 0.7')

Program: CD-HIT, V4.8.1 (+OpenMP), Apr 07 2021, 10:57:21
Command: cd-hit -i Nucleus_data.fasta -o
         Nucleus_cd-hit_data.txt -c 0.7

Started: Fri May 31 12:47:43 2024
                            Output                              
----------------------------------------------------------------
total seq: 3015
longest and shortest : 3412 and 66
Total letters: 1751320
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 2M
Buffer          : 1 X 11M = 11M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 78M

Table limit with the given memory limit:
Max number of representatives: 821959
Max number of word counting entries: 90149660

comparing sequences from          0  to       3015


...
     3015  finished        478  clusters

Approximated maximum memory consumption: 81M
writing new database
writing clustering information
program completed !

Total CPU time 1.43


0

In [154]:
import csv

# Input and output file paths
input_file = 'Nucleus_cd-hit_data.txt'
output_file = 'pos_nuc_data.csv'

# Initialize a list to hold sequences
sequences = []

# Read the CD-HIT output file
with open(input_file, 'r') as file:
    for line in file:
        line = line.strip()  # Remove leading/trailing whitespace
        if not line.startswith('>'):  # Ignore lines starting with '>'
            sequences.append([line])  # Add the sequence to the list

# Write the sequences to a CSV file
with open(output_file, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Sequence'])  # Write the header
    writer.writerows(sequences)  # Write the sequences

print(f"Sequences have been successfully saved to {output_file}")


Sequences have been successfully saved to pos_nuc_data.csv


In [155]:
import csv

# Input and output file paths
input_file = 'Neg_nuc_cd-hit_data.txt'
output_file = 'Neg_N_data.csv'

# Initialize a list to hold sequences
sequences = []

# Read the CD-HIT output file
with open(input_file, 'r') as file:
    for line in file:
        line = line.strip()  # Remove leading/trailing whitespace
        if not line.startswith('>'):  # Ignore lines starting with '>'
            sequences.append([line])  # Add the sequence to the list

# Write the sequences to a CSV file
with open(output_file, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Sequence'])  # Write the header
    writer.writerows(sequences)  # Write the sequences

print(f"Sequences have been successfully saved to {output_file}")


Sequences have been successfully saved to Neg_N_data.csv


In [156]:
import pandas as pd

# File path
file_path = 'Neg_N_data.csv'

# Read the existing CSV file
df = pd.read_csv(file_path)

# Add a new column with a default value of 1
df['Label'] = 1

# Write the updated dataframe back to the same CSV file
df.to_csv(file_path, index=False)

print(f"New column 'Label' with value 1 added to {file_path}")


New column 'Label' with value 1 added to Neg_N_data.csv


In [157]:
import pandas as pd

# File path
file_path = 'pos_nuc_data.csv'

# Read the existing CSV file
df = pd.read_csv(file_path)

# Add a new column with a default value of 0
df['Label'] = 0

# Write the updated dataframe back to the same CSV file
df.to_csv(file_path, index=False)

print(f"New column 'Label' with value 0 added to {file_path}")


New column 'Label' with value 0 added to pos_nuc_data.csv


In [158]:
data1 = pd.read_csv("Neg_N_data.csv")
data2 = pd.read_csv("pos_nuc_data.csv")

In [159]:
# Merge the two DataFrames
merged_df = pd.concat([data1, data2], ignore_index=True)

# Write the merged DataFrame to a new CSV file
merged_df.to_csv('merged_nuc_data.csv', index=False)
print('file is merged successfully')

data = merged_df.sample(frac=1)

file is merged successfully


In [160]:
X = data['Sequence']
y = data['Label']

In [161]:
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [162]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [163]:
# Define the unique amino acids
amino_acids = 'ACDEFGHIKLMNPQRSTVWY'

# Function to calculate amino acid composition
def calculate_aa_composition(sequence):
    composition = np.zeros(len(amino_acids))
    for aa in sequence:
        if aa in amino_acids:
            index = amino_acids.index(aa)
            composition[index] += 1
    # Normalize by sequence length
    return composition / len(sequence)



# Create features based on amino acid composition
X_train_aa_composition = [calculate_aa_composition(seq) for seq in X_train]
X_test_aa_composition = [calculate_aa_composition(seq) for seq in X_test]

In [164]:
X_test_aa_composition


[array([0.06713781, 0.00353357, 0.0565371 , 0.09540636, 0.03886926,
        0.05300353, 0.02826855, 0.08127208, 0.07420495, 0.06360424,
        0.02120141, 0.05300353, 0.05300353, 0.0565371 , 0.03533569,
        0.04946996, 0.0565371 , 0.07067138, 0.01413428, 0.02826855]),
 array([0.04918033, 0.01639344, 0.0557377 , 0.07213115, 0.0557377 ,
        0.07213115, 0.01311475, 0.05901639, 0.10163934, 0.10163934,
        0.00983607, 0.0557377 , 0.06229508, 0.03278689, 0.04918033,
        0.04262295, 0.03606557, 0.06885246, 0.01311475, 0.03278689]),
 array([0.0608365 , 0.01901141, 0.0418251 , 0.1026616 , 0.02281369,
        0.07984791, 0.01520913, 0.03802281, 0.11026616, 0.08365019,
        0.01140684, 0.02281369, 0.05323194, 0.03802281, 0.06463878,
        0.05703422, 0.08365019, 0.05703422, 0.01520913, 0.02281369]),
 array([0.07684098, 0.01387407, 0.05549626, 0.05549626, 0.0298826 ,
        0.03521878, 0.02454642, 0.05763074, 0.05869797, 0.08858058,
        0.02454642, 0.05229456, 0.06189968

In [165]:
# Train the SVM model using the features based on amino acid composition
svm_model_aa = SVC(kernel='rbf', C=1.0, gamma='scale', probability=True)  # Set probability=True
svm_model_aa.fit(X_train_aa_composition, y_train)

# Evaluate the model
y_pred_aa = svm_model_aa.predict(X_test_aa_composition)
accuracy_aa = accuracy_score(y_test, y_pred_aa)
print("Accuracy based on amino acid composition:", accuracy_aa)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_aa)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy based on amino acid composition: 0.7388535031847133
Confusion Matrix:
[[82  8]
 [33 34]]
